#!/bin/bash

set -e

tools/gen_memory_circuit \
    --patch_diameter 3 4 5 6 7 8 9 10 11 \
    --rounds "10*d" \
    --noise_strength 1e-3 \
    --gateset cz \
    --patches 1 \
    --yokes 1 \
    --remove_x_yoke \
    --out_dir out/gap_circuits
