"""Strict detector-layout compilation for the L1 ProMatch experiment."""

from __future__ import annotations

import dataclasses
import hashlib
import json
import math
from typing import Literal, TypeAlias

import stim


_COORD_ATOL = 1e-7


@dataclasses.dataclass(frozen=True, order=True)
class L1WindowDomain:
    patch_id: int
    check_basis: Literal["X", "Z"]
    window_id: int


@dataclasses.dataclass(frozen=True, order=True)
class L1FullHistoryDomain:
    patch_id: int
    check_basis: Literal["X", "Z"]


L1DomainKey: TypeAlias = L1WindowDomain | L1FullHistoryDomain


@dataclasses.dataclass(frozen=True, order=True)
class L1BodyDetector:
    patch_id: int
    check_basis: Literal["X", "Z"]
    time: int
    window_id: int


@dataclasses.dataclass(frozen=True, order=True)
class L1TerminalDetector:
    patch_id: int
    check_basis: Literal["X", "Z"]
    time: int


@dataclasses.dataclass(frozen=True, order=True)
class YokeDetector:
    pass


DetectorRole: TypeAlias = L1BodyDetector | L1TerminalDetector | YokeDetector


@dataclasses.dataclass(frozen=True)
class PromatchLayout:
    """Validated assignment of every DEM detector to an L1 or outer role."""

    mode: Literal["windowd", "fullhistory"]
    distance: int
    rounds: int
    pitch: int
    num_patches: int
    num_windows: int
    coordinates: tuple[tuple[float, ...], ...]
    roles: tuple[DetectorRole, ...]
    detector_domains: tuple[L1DomainKey | None, ...]
    domains: tuple[L1DomainKey, ...]
    domain_detector_ids: dict[L1DomainKey, tuple[int, ...]]
    body_detector_ids: tuple[int, ...]
    terminal_detector_ids: tuple[int, ...]
    yoke_detector_ids: tuple[int, ...]
    fingerprint: str

    @property
    def num_detectors(self) -> int:
        return len(self.roles)

    @property
    def d(self) -> int:
        return self.distance

    @property
    def r(self) -> int:
        return self.rounds

    def role_of(self, detector_id: int) -> DetectorRole:
        return self.roles[detector_id]

    def domain_of(self, detector_id: int) -> L1DomainKey | None:
        return self.detector_domains[detector_id]

    def observable_owner(self, observable_id: int) -> int:
        if observable_id < 0 or observable_id >= 2 * self.num_patches:
            raise ValueError(
                f"observable ID {observable_id} outside [0, {2 * self.num_patches})"
            )
        return observable_id // 2


def _close(actual: float, expected: float) -> bool:
    return math.isclose(actual, expected, rel_tol=0, abs_tol=_COORD_ATOL)


def _integer_coordinate(value: float, *, detector_id: int, name: str) -> int:
    result = round(value)
    if not _close(value, result):
        raise ValueError(
            f"detector {detector_id} has non-integral {name} coordinate {value!r}"
        )
    return int(result)


def _maintained_spatial_template(
    distance: int,
) -> set[tuple[float, float, Literal["X", "Z"]]]:
    """Exact stabilizer-center template generated by the maintained patch."""

    interior = tuple(k + 0.5 for k in range(distance - 1))
    positions: set[tuple[float, float]] = {
        (x, y) for x in interior for y in interior
    }
    for x in interior:
        if round(x - 0.5) % 2 == 0:
            positions.add((x, -0.5))
        if round(x + distance - 0.5) % 2 == 0:
            positions.add((x, distance - 0.5))
    for y in interior:
        if round(-0.5 + y) % 2 == 1:
            positions.add((-0.5, y))
        if round(distance - 0.5 + y) % 2 == 1:
            positions.add((distance - 0.5, y))
    result = {
        (x, y, "X" if round(x + y) % 2 == 0 else "Z")
        for x, y in positions
    }
    if len(result) != distance * distance - 1:
        raise AssertionError("internal maintained-patch template has the wrong size")
    return result


def _layout_fingerprint(
    *,
    mode: str,
    distance: int,
    rounds: int,
    coordinates: tuple[tuple[float, ...], ...],
    detector_domains: tuple[L1DomainKey | None, ...],
) -> str:
    domain_rows = []
    for domain in detector_domains:
        if domain is None:
            domain_rows.append(None)
        elif isinstance(domain, L1WindowDomain):
            domain_rows.append(["window", domain.patch_id, domain.check_basis, domain.window_id])
        else:
            domain_rows.append(["full", domain.patch_id, domain.check_basis])
    payload = {
        "schema": "promatch-layout-v1",
        "mode": mode,
        "distance": distance,
        "rounds": rounds,
        "coordinates": coordinates,
        "detector_domains": domain_rows,
    }
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


def compile_layout(
    dem: stim.DetectorErrorModel,
    *,
    mode: Literal["windowd", "fullhistory"] = "windowd",
) -> PromatchLayout:
    """Compiles and validates the maintained 1D yoked-memory detector layout.

    The validation is intentionally strict. A structurally unsupported DEM is an
    error instead of an invitation to run a global or partially classified
    predecoder.
    """

    if not isinstance(dem, stim.DetectorErrorModel):
        raise TypeError(f"dem must be a stim.DetectorErrorModel, got {type(dem)!r}")
    if mode not in ("windowd", "fullhistory"):
        raise ValueError(f"unsupported ProMatch layout mode {mode!r}")
    if dem.num_detectors == 0:
        raise ValueError("supported yoked-memory DEMs must contain detectors")

    raw_coordinates = dem.get_detector_coordinates()
    expected_ids = set(range(dem.num_detectors))
    actual_ids = set(raw_coordinates)
    if actual_ids != expected_ids:
        missing = sorted(expected_ids - actual_ids)
        extra = sorted(actual_ids - expected_ids)
        raise ValueError(
            "DEM must have exactly one coordinate record per detector; "
            f"missing={missing[:8]}, extra={extra[:8]}"
        )

    coordinates: list[tuple[float, ...]] = []
    inner_ids: list[int] = []
    yoke_ids: list[int] = []
    for detector_id in range(dem.num_detectors):
        coordinate = tuple(float(v) for v in raw_coordinates[detector_id])
        if len(coordinate) < 3:
            raise ValueError(
                f"detector {detector_id} needs at least (x, y, t); got {coordinate!r}"
            )
        if not all(math.isfinite(v) for v in coordinate):
            raise ValueError(f"detector {detector_id} has nonfinite coordinates {coordinate!r}")
        coordinates.append(coordinate)
        if _close(coordinate[1], -2):
            yoke_ids.append(detector_id)
        else:
            inner_ids.append(detector_id)

    if not inner_ids:
        raise ValueError("supported yoked-memory DEMs must contain inner detectors")
    if len(yoke_ids) not in (1, 2):
        raise ValueError(
            "supported 1D yoked-memory DEMs have one dummy/single-yoke detector "
            f"or two yoke detectors; found {len(yoke_ids)}"
        )

    ys = [coordinates[k][1] for k in inner_ids]
    min_y = min(ys)
    max_y = max(ys)
    distance = round(max_y - min_y)
    if distance < 2:
        raise ValueError(f"inferred invalid patch distance {distance}")
    if not _close(min_y, -0.5) or not _close(max_y, distance - 0.5):
        raise ValueError(
            "inner y extent is incompatible with the maintained 1D geometry: "
            f"min_y={min_y}, max_y={max_y}, inferred_d={distance}"
        )
    pitch = distance + 1

    # First classify spatial coordinates and integer times. Roles are assigned
    # after the terminal time and window count have been validated.
    spatial: dict[int, tuple[int, Literal["X", "Z"], float, float, int]] = {}
    inner_times: set[int] = set()
    patch_ids: set[int] = set()
    for detector_id in inner_ids:
        x, y, t = coordinates[detector_id][:3]
        time = _integer_coordinate(t, detector_id=detector_id, name="time")
        if time < 0:
            raise ValueError(f"detector {detector_id} has negative time {time}")
        patch_id = math.floor((x + 0.5 + _COORD_ATOL) / pitch)
        local_x = x - patch_id * pitch
        if patch_id < 0 or local_x < -0.5 - _COORD_ATOL or local_x > distance - 0.5 + _COORD_ATOL:
            raise ValueError(
                f"detector {detector_id} at x={x} does not fit a maintained 1D patch"
            )
        if not _close(2 * local_x, round(2 * local_x)):
            raise ValueError(f"detector {detector_id} has invalid local x={local_x}")
        if not _close(2 * y, round(2 * y)):
            raise ValueError(f"detector {detector_id} has invalid y={y}")
        local_x = round(2 * local_x) / 2
        y = round(2 * y) / 2
        parity_coordinate = local_x + y
        parity = round(parity_coordinate)
        if not _close(parity_coordinate, parity):
            raise ValueError(
                f"detector {detector_id} is off the checkerboard lattice: "
                f"local_x+y={parity_coordinate}"
            )
        basis: Literal["X", "Z"] = "X" if int(parity) & 1 == 0 else "Z"
        spatial[detector_id] = (patch_id, basis, local_x, y, time)
        inner_times.add(time)
        patch_ids.add(patch_id)

    if not patch_ids or patch_ids != set(range(max(patch_ids) + 1)):
        raise ValueError(f"inner patch IDs are not contiguous from zero: {sorted(patch_ids)}")
    num_patches = len(patch_ids)
    if dem.num_observables != 2 * num_patches:
        raise ValueError(
            "v1 requires exactly two observables per patch "
            f"(remove_x_yoke=False); got {dem.num_observables} observables and "
            f"{num_patches} patches"
        )

    rounds = max(inner_times)
    if rounds < 2 or inner_times != set(range(rounds + 1)):
        raise ValueError(
            "maintained magic-boundary inner times must be exactly {0, ..., r} "
            f"with r>=2; got {sorted(inner_times)}"
        )
    if mode == "windowd" and rounds % distance:
        raise ValueError(
            f"windowd requires rounds divisible by distance; got r={rounds}, d={distance}"
        )
    num_windows = math.ceil(rounds / distance)

    # Every patch and every time must expose the same local stabilizer layout.
    spatial_by_patch_time_lists: dict[
        tuple[int, int], list[tuple[float, float, str]]
    ] = {}
    for patch_id, basis, local_x, y, time in spatial.values():
        spatial_by_patch_time_lists.setdefault((patch_id, time), []).append(
            (local_x, y, basis)
        )
    spatial_by_patch_time: dict[
        tuple[int, int], set[tuple[float, float, str]]
    ] = {}
    for key, entries in spatial_by_patch_time_lists.items():
        unique = set(entries)
        if len(unique) != len(entries):
            raise ValueError(
                "duplicate inner detector coordinate at "
                f"patch={key[0]}, time={key[1]}"
            )
        spatial_by_patch_time[key] = unique

    reference = spatial_by_patch_time[(0, 0)]
    if not reference:
        raise ValueError("patch 0 time 0 has no inner detectors")
    expected_template = _maintained_spatial_template(distance)
    if reference != expected_template:
        missing = sorted(expected_template - reference)
        extra = sorted(reference - expected_template)
        raise ValueError(
            "patch 0 time 0 does not match the maintained stabilizer layout: "
            f"missing={missing[:8]}, extra={extra[:8]}"
        )
    for patch_id in range(num_patches):
        for time in range(rounds + 1):
            actual = spatial_by_patch_time.get((patch_id, time))
            if actual != reference:
                raise ValueError(
                    "inconsistent local detector layout at "
                    f"patch={patch_id}, time={time}: expected {len(reference)} sites, "
                    f"got {0 if actual is None else len(actual)}"
                )

    for detector_id in yoke_ids:
        x, y, t = coordinates[detector_id][:3]
        if not _close(x, 0) or not _close(y, -2):
            raise ValueError(
                f"yoke detector {detector_id} must be at reserved (x,y)=(0,-2); "
                f"got ({x},{y})"
            )
        yoke_time = _integer_coordinate(t, detector_id=detector_id, name="yoke time")
        if yoke_time != rounds:
            raise ValueError(
                f"yoke detector {detector_id} must be at terminal time {rounds}; "
                f"got {yoke_time}"
            )

    roles: list[DetectorRole | None] = [None] * dem.num_detectors
    detector_domains: list[L1DomainKey | None] = [None] * dem.num_detectors
    domain_detector_lists: dict[L1DomainKey, list[int]] = {}
    body_ids: list[int] = []
    terminal_ids: list[int] = []
    for detector_id in inner_ids:
        patch_id, basis, _, _, time = spatial[detector_id]
        if time == rounds:
            role: DetectorRole = L1TerminalDetector(patch_id, basis, time)
            terminal_ids.append(detector_id)
        else:
            window_id = time // distance
            role = L1BodyDetector(patch_id, basis, time, window_id)
            if mode == "windowd":
                domain: L1DomainKey = L1WindowDomain(patch_id, basis, window_id)
            else:
                domain = L1FullHistoryDomain(patch_id, basis)
            detector_domains[detector_id] = domain
            domain_detector_lists.setdefault(domain, []).append(detector_id)
            body_ids.append(detector_id)
        roles[detector_id] = role
    for detector_id in yoke_ids:
        roles[detector_id] = YokeDetector()

    if any(role is None for role in roles):
        raise AssertionError("internal error: detector role assignment was incomplete")
    concrete_roles = tuple(roles)  # type: ignore[arg-type]
    concrete_domains = tuple(detector_domains)
    domains = tuple(sorted(domain_detector_lists))
    expected_domains = num_patches * 2 * (num_windows if mode == "windowd" else 1)
    if len(domains) != expected_domains:
        raise ValueError(
            f"expected {expected_domains} nonempty L1 domains, found {len(domains)}"
        )
    domain_detector_ids = {
        domain: tuple(sorted(domain_detector_lists[domain])) for domain in domains
    }
    coordinate_tuple = tuple(coordinates)
    fingerprint = _layout_fingerprint(
        mode=mode,
        distance=distance,
        rounds=rounds,
        coordinates=coordinate_tuple,
        detector_domains=concrete_domains,
    )

    return PromatchLayout(
        mode=mode,
        distance=distance,
        rounds=rounds,
        pitch=pitch,
        num_patches=num_patches,
        num_windows=num_windows,
        coordinates=coordinate_tuple,
        roles=concrete_roles,
        detector_domains=concrete_domains,
        domains=domains,
        domain_detector_ids=domain_detector_ids,
        body_detector_ids=tuple(sorted(body_ids)),
        terminal_detector_ids=tuple(sorted(terminal_ids)),
        yoke_detector_ids=tuple(sorted(yoke_ids)),
        fingerprint=fingerprint,
    )
