#!/usr/bin/env python3
"""Runs `sinter plot` with the given arguments, then prints a link to --out.

All command line arguments are forwarded unchanged to `sinter plot` (run
`sinter plot --help` for the available plotting options). After a successful
plot, the path given via --out is echoed as a clickable file:// link.
"""

import pathlib
import subprocess
import sys

if '-h' in sys.argv[1:] or '--help' in sys.argv[1:]:
    print(__doc__)
    sys.exit(0)

try:
    subprocess.check_output([
        'sinter',
        'plot',
        *sys.argv[1:],
    ], stderr=sys.stderr)
except subprocess.CalledProcessError as e:
    if e.output:
        sys.stderr.buffer.write(e.output)
        sys.stderr.buffer.flush()
    print(f'sinter plot failed with exit code {e.returncode}', file=sys.stderr)
    sys.exit(e.returncode)

if '--out' in sys.argv:
    path = sys.argv[sys.argv.index('--out') + 1]
    print(f'wrote file://{pathlib.Path(path).absolute()}')
